auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: linzhi
production_url : http://linzhi.github.io
me: https://github.com/linzhi


author :
  name : linzhi
  github : linzhi
  
feed: /atom.xml
